### PR TITLE
Add casing aliases for Maid class methods

### PR DESCRIPTION
**Pull request by ReturnedTrue**
First ever PR to a project, hope I did fine.

Fixes issue: #147

### CODE REVIEW

**Comment by colbert2677** [comment]
If you're adding camelCase aliases for all Maid methods, should you not also add a camelCase variant for DoCleaning? I feel like it'd be more complete of a job that way.

**Comment by ReturnedTrue** [comment]
Good point, added it.

**Comment by sayhisam1** [comment]
This should also add casing aliases for objects added to the maid (e.g. maid should check if an object has a `destroy` method, in addition to the current check for `Destroy`)

**Comment by Quenty** [comment]
Probably not going to merge this, sorry! I had variable casing in Nevermore for a while but it became a pain to maintain.

In the future, I'd like to switch syntax to `:lowerCamelCase()` but this will require a significant refactor. Now that we have versioning, you should be able to fork maid pretty easily. We may also be able to reversion packages if we refactor to :lowerCamelCase().

**Pull request closed without merging**
