### PR TITLE
Switch to an image with less harsh edge lines

### PR DESCRIPTION
**Pull request by Validark**
Top is old, bottom is new

It's might be difficult to see in this image, but in motion, there is an obvious difference. The top one has significantly darker edges.

### CODE REVIEW

**Comment by Quenty** [comment]
I actually have another image that I'm standardizing for circle usage that should be used in this place to avoid pulling multiple circles in. 

I'll reconsider in a bit see if it looks different.

**Comment by Quenty** [comment]
The AssetID is rbxassetid://633244888 with a 256 x 256 white circle. I'm going to make a pull request to your branch to set it to this.

**Comment by Quenty** [comment]
Actually, it's going to be easier to either have you make the pull request to me, or for me to just change Nevermore. Let me know.

**Comment by Validark** [comment]
Fixed

**Comment by Quenty** [comment]
Thank you!

**Comment by Quenty** [comment]
These changes were merged into version2 too! Thanks!

**Comment by Validark** [comment]
Please add in some example code for your libraries.

**Comment by Quenty** [comment]
This isn't the right place to discuss this, but it'd be good to write / automate tests on Nevermore.

I'm looking into moving Nevermore towards a more general package manager. However, this will have to wait until later.

**Comment by Validark** [comment]
If only we had like a Discord server or something where it would be appropriate to have a discussion...

**Comment by Validark** [comment]
Sorry. I thought about that comment, I didn't mean it as rude as it may have came out. Could we connect on Discord?

**Comment by Quenty** [comment]
Sure! Discord made! https://discord.gg/mhtGUS8

**Pull request merged**
