### PR TITLE
Procedurally Generate GetRemoteEvent+Function

### PR DESCRIPTION
**Pull request by Narrev**
This new version is shorter, more efficient, has a more flexible syntax, supports managing more instances other than just RemoteEvents and RemoteFunctions, and supports Appendages! More information about Appendages here: https://github.com/Narrev/Nevermore
Also, completely backwards compatible!
And it comes with a built-in (generated) Folder manager for use with the NevermoreResources folder!

### CODE REVIEW

**Comment by Quenty** [comment]
Looks pretty good. Will be looking into this implementation more before merging.

**Comment by Narrev** [comment]
I realized that I didn't change the FolderName in config back to "Nevermore". I have been using "Modules" because it's more intuitive, but I recognize that the Nevermore setup code creates a folder named "Nevermore". 

This may have prevented this new version from working for you if you didn't catch this.

It now should be fully capable of running your codebase.

**Comment by Quenty** [comment]
Looking very good. Is "extract" intentionally lower case? If not, we should change it. A style guide on the wiki would also be good.

**Comment by Narrev** [comment]
Yes, `extract` is intentionally lowercase. It is meant to mimic the syntax for `select`

**Comment by Narrev** [comment]
Why hasn't this been implemented yet?

**Comment by Narrev** [comment]
Outdated

**Pull request closed without merging**
